### ISSUE TITLE
BDK Chain Meeting 11 (`bdk_chain` Redesign)

### ISSUE THREAD

**Issue by evanlinjin** [bitcoindevkit/.github#51]
Main ticket: https://github.com/bitcoindevkit/bdk/issues/895
Evan's thoughts: https://hackmd.io/@evanlinjin/bdk_chain_redesign_thoughts
Meeting minutes: https://hackmd.io/@evanlinjin/bdk_core_11

**Comment by notmandatory** [comment]
I updated or added the below now `BDK 1.0.0` labeled issues based on @evanlinjin 's excellent notes:

bitcoindevkit/bdk#331
bitcoindevkit/bdk#917
bitcoindevkit/bdk#918
bitcoindevkit/bdk#919
bitcoindevkit/bdk#920
bitcoindevkit/bdk#921
bitcoindevkit/bdk#922
bitcoindevkit/bdk#923
